const episodes = [

{ 
    
    //สำนักถังเลิศภพจบแดน (ถังซาน2)
    name: "ตอนที่ 134", 
    servers: {
        //"ตัวเล่นหลัก": "https://drive.google.com/file/d/1Xk2LtLUggXYxmEQpmNdF6hwVk3v_GzNo/preview",
        "สำรอง 1": "https://ok.ru/videoembed/10775279372808?nochat=1",
        "สำรอง 2": "ลิงก์อื่น..."
    }
},

    {
    name: "ตอนที่ 135", 
    servers: {
        "ตัวเล่นหลัก": "https://ok.ru/videoembed/10816247171592?nochat=1",
        "สำรอง 1":  "https://drive.google.com/file/d/1Xk2LtLUggXYxmEQpmNdF6hwVk3v_GzNo/preview",
        //"สำรอง 2": "https://t.me/nnasubtelegram/418?embed=1",
    }
},

{
    name: "ตอนที่ 136", 
    servers: {
        "ตัวเล่นหลัก": "https://drive.google.com/file/d/1P_RAxiNtYie7e9YzxglLLXfOpaLwi2mT/preview",
        "สำรอง 1":  "https://ok.ru/videoembed/10947992357384?nochat=1",
        //"สำรอง 2": "https://t.me/nnasubtelegram/418?embed=1",
    }
},

{
    name: "ตอนที่ 137", 
    servers: {
        "ตัวเล่นหลัก": "https://",
        "สำรอง 1":  "/preview",
        //"สำรอง 2": "https://t.me/nnasubtelegram/418?embed=1",
    }
},


];
